config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get "/signup", to: "users#new"
  post '/signup',  to: 'users#create'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :microposts
  resources :contacts
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
 
  attr_accessor :remember_token
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX}, 
            uniqueness: {case_sensitive: false}#大文字小文字を識別する→false
  has_secure_password           
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true 
  mount_uploader :image_name, ImageNameUploader
  
 class << self
  # 渡された文字列のハッシュ値を返す
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def new_token
    SecureRandom.urlsafe_base64
  end
 end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    #remember_tokenに要素を代入
    #（selfを付けるとクラス変数になる→この場合User.remember_tokenと同意）
    self.remember_token = User.new_token
    #validationを無視して更新　（:remember_digest属性にハッシュ化したremember_tokenを）
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  def posts
    return Micropost.where(user_id: self.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :authenticate_user, only: [:index, :show, :edit, :update, :destroy]
  
  def index
   @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "ログインしました。"
      redirect_to @user
    else
      render "new"
    end
  end
  
  def edit
  
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_url
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image_name)
    end  
    
    # beforeアクション
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
       redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  # 渡されたユーザーのGravatar画像を返す
  #def gravatar_for(user, options = { size: 80 })
    #gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #size = options[:size]
    #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #image_tag(gravatar_url, alt: user.name, class: "gravatar")
  #end
  

end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
      
  <%= f.label :name, "お名前（必須）" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, "メールアドレス（必須）" %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "パスワード（必須）" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード再入力（必須）" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <p>※必須項目は必ずご入力ください</p>

  <%= f.label :image_name, "アイコン" %>
  <%= f.file_field :image_name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn-area" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% if user.image_name? %>
    <%= image_tag user.image_name, class: "avater_image" %>
  <% else %>
    <img src="/user_images/avater.jpg", class="avater_image" >
   <% end %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to "削除", user, method: :delete,
                              data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "編集") %>
<% provide(:url, user_path)  %>
<% provide(:button_text, "更新")  %>
<h1>プロフィールの編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>
<% provide(:url, signup_path)  %>
<% provide(:button_text, "新規登録")  %>
<h1 class = "main">新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="main row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if @user.image_name? %>
          <%= image_tag @user.image_name, class: "avater_image" %>
        <% else %>
          <img src="/user_images/avater.jpg", class="avater_image" >
        <% end %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>投稿一覧 (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>