config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get "/signup", to: "users#new"
  post '/signup',  to: 'users#create'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :microposts
  resources :contacts
  resources :likes, only: [:create, :destroy]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true  
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました'
      redirect_to root_path
    else
      render :new
    end
  end
  
  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/new.html.erb
<% provide(:title, "お問い合わせ") %>
<div class = "contact-main">
 <h2>お問い合わせ</h2>
 <div class="row">
  <div class="col-md-6 col-md-offset-3">
　  <%= form_for(@contact, url: contacts_path) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
      
    <%= f.label :name, "お名前（必須）" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "メールアドレス（必須）" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :message, "お問い合わせ内容（必須）" %>
    <%= f.text_area :message, class: 'form-control', placeholder: "ご入力ください" %>

  　
    <p>※必須項目は必ずご入力ください</p>

    <%= f.submit "送信", class: "btn-area" %>
　<% end %>
　</div>
 </div>
</div>