config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get "/signup", to: "users#new"
  post '/signup',  to: 'users#create'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :microposts
  resources :contacts
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "TOP",   root_path %></li>
      <% if logged_in? %>
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <li><%= link_to "投稿一覧", microposts_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            プライベート <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
            <li><%= link_to "編集", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | 石原農園</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
    <script src="https://kit.fontawesome.com/d41a77a2e5.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="https://ao-system.net/favicon/tmp/15948846552243CjLXSpSq32.png" type="image/png" />   
    <link rel="icon" href="https://ao-system.net/favicon/tmp/15948846552243CjLXSpSq32.png" type="image/png" /> 
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="flash">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      </div>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>